fix

diff --git a/debian b/debian
--- a/debian
+++ b/debian
@@ -198,22 +198,29 @@ fi
 
 base="https://debian.lol"
 github_base="https://raw.githubusercontent.com/mysqto/install/gh-pages"
+gh_proxy_base="https://ghp.ci/https://raw.githubusercontent.com/mysqto/install/gh-pages"
 
 # check connection to base url
 if ! curl -sL --connect-timeout 5 "$base" >/dev/null 2>&1; then
-    echo "Failed to connect to $base"
-    echo "try to use github url $github_base"
+    warn "Failed to connect to $base"
+    info "try to use github url $github_base"
     base="$github_base"
     # check connection to base url again
     if ! curl -sL --connect-timeout 5 "$base" >/dev/null 2>&1; then
-        echo "Failed to connect to $base"
-        exit 1
+        warn "Failed to connect to $base"
+        info "try to use ghproxy url"
+    fi
+
+    base="$gh_proxy_base"
+    # check connection to base url again
+    if ! curl -sL --connect-timeout 5 "$base" >/dev/null 2>&1; then
+        error "Failed to connect to $base"
     fi
 fi
 
 # debug flag
 dry_run=false
-# systen related
+# system related
 arch=
 version=stable
 suite=
