shell format

diff --git a/im b/im
--- a/im
+++ b/im
@@ -2,6 +2,38 @@
 
 lookbusy_base="http://www.devin.com/lookbusy/"
 
+function get_disk() {
+    lsblk -oMOUNTPOINT,PKNAME -P | grep 'MOUNTPOINT="/"' | cut -d'"' -f4 | sed 's/[0-9]//g'
+}
+
+# shellcheck disable=SC2317
+function distro() {
+    dist="$(lsb_release -is 2>/dev/null)"
+    [ -n "$dist" ] || dist="$(cat /etc/*-release 2>/dev/null | grep -Eo 'ID=\w+' | cut -d'=' -f2 | head -n1)"
+    [ -n "$dist" ] || dist="$(cat /etc/*-release 2>/dev/null | grep -Eo 'ID_LIKE=\w+' | cut -d'=' -f2 | head -n1)"
+    echo "$dist" | tr '[:upper:]' '[:lower:]'
+}
+
+function arch() {
+    arch=$(dpkg --print-architecture 2>/dev/null) || {
+        case $(uname -m) in
+        x86_64)
+            arch=amd64
+            ;;
+        aarch64)
+            arch=arm64
+            ;;
+        i386)
+            arch=i386
+            ;;
+        *)
+            err 'No "--architecture" specified'
+            ;;
+        esac
+    }
+    echo "$arch"
+}
+
 function add_cronjob() {
     username="$1"
     # all the other arguments are the command
@@ -22,7 +54,10 @@ function add_cronjob() {
     fi
 
     # add the job to crontab
-    (crontab -u "$username" -l 2>/dev/null; echo "$cron # $cron_checksum") | crontab -u "$username" -
+    (
+        crontab -u "$username" -l 2>/dev/null
+        echo "$cron # $cron_checksum"
+    ) | crontab -u "$username" -
 }
 
 function installed() {
@@ -30,19 +65,19 @@ function installed() {
 }
 
 function updateable() {
-    apt-get update > /dev/null 2>&1
+    apt-get update >/dev/null 2>&1
     available=$(apt list --upgradable 2>/dev/null | grep -c upgradable)
     [[ "$available" -gt 0 ]] || return 1
 }
 
 function updatable_without_kernel() {
-    apt-get update > /dev/null 2>&1
+    apt-get update >/dev/null 2>&1
     available=$(apt list --upgradable 2>/dev/null | grep -v linux-image | grep -c upgradable)
     [[ "$available" -gt 0 ]] || return 1
 }
 
 function kernal_updateable() {
-    apt-get update > /dev/null 2>&1
+    apt-get update >/dev/null 2>&1
     available=$(apt list --upgradable 2>/dev/null | grep upgradable | grep -c linux-image)
     [[ "$available" -gt 0 ]] || return 1
 }
@@ -54,6 +89,18 @@ function remove_old_kernels() {
         apt -y purge "$kernel"
     done
     apt -y autoremove && apt -y autoclean
+}
+
+function fix_grub() {
+    dist="$(distro)"
+    [[ "$dist" != "debian" ]] && warn "not an Debian server, no need to fix grub" && return 0
+    # re-install grub to fix the grub menu
+    disk=$(get_disk)
+    [[ -z "$disk" ]] && warn "failed to get the disk" && return
+    [[ "$disk" =~ ^/dev/ ]] || disk="/dev/$disk"
+    arch="$(uname -m)" || err "failed to get the architecture"
+    grub-install "$disk" --"$arch"-efi --efi-directory=/boot/efi --boot-directory=/boot --recheck
+    update-grub
 }
 
 function update() {
@@ -70,11 +117,13 @@ function update() {
 }
 
 function upgrade() {
+    dist="$(distro)"
+    [[ "$dist" != "Ubuntu" ]] && echo "not an Ubuntu server, no need to upgrade" && return 0
     current_version=$(lsb_release -r | awk '{print $2}')
     [[ "$current_version" == "22.04" ]] && echo "already on 22.04, no need to upgrade" && return 0
     echo "upgrading the server from $current_version to 22.04"
     [[ -f /etc/apt/apt.conf.d/local ]] && cp /etc/apt/apt.conf.d/local /etc/apt/apt.conf.d/local.bak
-    echo 'DPkg::options { "--force-confdef"; "--force-confold"; }' > /etc/apt/apt.conf.d/local
+    echo 'DPkg::options { "--force-confdef"; "--force-confold"; }' >/etc/apt/apt.conf.d/local
     DEBIAN_FRONTEND=noninteractive /usr/bin/do-release-upgrade -d -f DistUpgradeViewNonInteractive
     [[ -f /etc/apt/apt.conf.d/local.bak ]] && cp /etc/apt/apt.conf.d/local.bak /etc/apt/apt.conf.d/local
     reboot
@@ -134,7 +183,7 @@ function self_update() {
     [[ -z "$new_script" ]] && echo "failed to get the latest script" && return 1
     script_path=$(readlink -f "$0")
     [[ ! -f "$script_path" ]] && echo "failed to get the script path" && return 1
-    (sleep 1 && cat <<< "$new_script" > "$script_path" && chmod +x "$script_path" && echo "script updated, please run it again") &
+    (sleep 1 && cat <<<"$new_script" >"$script_path" && chmod +x "$script_path" && echo "script updated, please run it again") &
     echo "im is updating, please wait"
 }
 
@@ -150,14 +199,12 @@ function reset() {
     local user="$2"
     [[ -z "$user" ]] && echo "username is required when reseting the server" && return 1
     case "$system" in
-        ubuntu)
-            curl -sL install.lol/ubuntu | bash -s -- -u "$user"
-            ;;
-        *)
-            curl -sL install.lol/debian | bash -s -- --user "$user"   \
-                       --bpo                                          \
-                       --provision
-            ;;
+    ubuntu)
+        curl -sL install.lol/ubuntu | bash -s -- -u "$user"
+        ;;
+    *)
+        curl -sL install.lol/debian | bash -s -- --user "$user" --bpo --provision
+        ;;
     esac
 }
 
@@ -184,19 +231,19 @@ function cleanup() {
 function netflix_test() {
     wd=$(mktemp -d -t netflix-XXXXXXXXXXXXXXXX 2>/dev/null)
     [[ -z "$wd" ]] && echo "failed to create a temp dir" && return 1
-    pushd "$wd" > /dev/null 2>&1 || return 1
-    rm -rf netflix-verify && git clone https://github.com/sjlleo/netflix-verify.git > /dev/null 2>&1 && \
+    pushd "$wd" >/dev/null 2>&1 || return 1
+    rm -rf netflix-verify && git clone https://github.com/sjlleo/netflix-verify.git >/dev/null 2>&1 &&
         cd netflix-verify && go run main.go && cd .. && rm -rf netflix-verify
-    popd > /dev/null 2>&1 || return 1
+    popd >/dev/null 2>&1 || return 1
     rm -rf "$wd"
 }
 
 function midea_unlock_test() {
     wd=$(mktemp -d -t midea-XXXXXXXXXXXXXXXX 2>/dev/null)
     [[ -z "$wd" ]] && echo "failed to create a temp dir" && return 1
-    pushd "$wd" > /dev/null 2>&1 || return 1
+    pushd "$wd" >/dev/null 2>&1 || return 1
     # TODO: add midea unlock test
-    popd > /dev/null 2>&1 || return 1
+    popd >/dev/null 2>&1 || return 1
     rm -rf "$wd"
 }
 
@@ -205,7 +252,7 @@ function install_edge_kernel() {
     apt -y update 2>/dev/null
     edge_kernel=$(apt-cache search -q linux-image-generic-hwe-"$(lsb_release -r | awk '{print $2}')"-edge 2>/dev/null | cut -d' ' -f1)
     [[ -z "$edge_kernel" ]] && echo "failed to get the edge kernel" && return 1
-    if dpkg -s "$edge_kernel" > /dev/null 2>&1; then
+    if dpkg -s "$edge_kernel" >/dev/null 2>&1; then
         echo "edge kernel already installed"
         return 0
     fi
@@ -223,11 +270,11 @@ function install_lookbusy() {
     [[ -z "$local_version" ]] || [[ "$local_version" != "$remote_version" ]] && {
         tmp_dir=$(mktemp -d -t lookbusy-XXXXXXXXXXXXXXXX 2>/dev/null)
         [[ -z "$tmp_dir" ]] && echo "failed to create a temp dir" && return 1
-        pushd "$tmp_dir" > /dev/null 2>&1 || return 1
+        pushd "$tmp_dir" >/dev/null 2>&1 || return 1
         curl -sL "$lookbusy_base$remote_url" -o lookbusy.tar.gz || return 1
         tar -xvf lookbusy.tar.gz --strip-components=1 --exclude=.svn || return 1
         ./configure && make && make install
-        popd > /dev/null 2>&1 || return 1
+        popd >/dev/null 2>&1 || return 1
         rm -rf "$tmp_dir"
     }
 }
@@ -270,14 +317,14 @@ function distro() {
 }
 
 if ((EUID != 0)); then
-	echo "Granting root privileges for ""$(basename "$0")"
-	if [[ -t 1 ]]; then
-		sudo "$0" "$@"
-	else
-		exec 1>output_file
-		gksu "$0" "$@"
-	fi
-	exit
+    echo "Granting root privileges for ""$(basename "$0")"
+    if [[ -t 1 ]]; then
+        sudo "$0" "$@"
+    else
+        exec 1>output_file
+        gksu "$0" "$@"
+    fi
+    exit
 fi
 
 _install_pyenv=false
@@ -336,29 +383,98 @@ POSITIONAL=()
 
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        -d | --distro ) _distro=true; shift 1 ;;
-        -uu | --update ) _update=true; shift 1 ;;
-        -uuu | --ugrade ) _upgrade=true; shift 1 ;;
-        -ui | --self-update ) _self_update=true; shift 1 ;;
-        -uss | --update-ss ) _update_ss=true; shift 1 ;;
-        -ro | --remove-old-kernels ) _remove_old_kernels=true; shift 1 ;;
-        -rr | --reset ) _reset=true; shift 1 ;;
-        -rrd | --reset-with-debian ) _reset_with_debian=true; shift 1 ;;
-        -rru | --reset-with-ubuntu ) _reset_with_ubuntu=true; shift 1 ;;
-        -r | --reboot ) _reboot=true; shift 1 ;;
-        -s | --midea-unlock-test ) _unlock_test=true; shift 1 ;;
-        -st | --speedtest ) _speedtest=true; shift 1 ;;
-        -a | --auto ) _auto=true; shift 1 ;;
-        -p | --provision ) _provision=true; shift 1 ;;
-        -u | --username ) username="$2"; shift 2 ;;
-        -c | --cleanup ) _cleanup=true; shift 1 ;;
-        -e | --edge-kernel ) _edge_kernel=true; shift 1 ;;
-        -l | --lookbusy ) _enable_lookbusy=true; shift 1 ;;
-        -ist | --install-speedtest ) _install_speedtest=true; shift 1 ;;
-        -ilb | --install-lookbusy ) _install_lookbusy=true; shift 1 ;;
-        -ipe | --install-pyenv ) _install_pyenv=true; shift 1 ;;
-        -nf | --netflix-test ) _netflix_test=true; shift 1 ;;
-        * ) POSITIONAL+=("$1"); shift ;;
+    -d | --distro)
+        _distro=true
+        shift 1
+        ;;
+    -uu | --update)
+        _update=true
+        shift 1
+        ;;
+    -uuu | --ugrade)
+        _upgrade=true
+        shift 1
+        ;;
+    -ui | --self-update)
+        _self_update=true
+        shift 1
+        ;;
+    -uss | --update-ss)
+        _update_ss=true
+        shift 1
+        ;;
+    -ro | --remove-old-kernels)
+        _remove_old_kernels=true
+        shift 1
+        ;;
+    -rr | --reset)
+        _reset=true
+        shift 1
+        ;;
+    -rrd | --reset-with-debian)
+        _reset_with_debian=true
+        shift 1
+        ;;
+    -rru | --reset-with-ubuntu)
+        _reset_with_ubuntu=true
+        shift 1
+        ;;
+    -r | --reboot)
+        _reboot=true
+        shift 1
+        ;;
+    -s | --midea-unlock-test)
+        _unlock_test=true
+        shift 1
+        ;;
+    -st | --speedtest)
+        _speedtest=true
+        shift 1
+        ;;
+    -a | --auto)
+        _auto=true
+        shift 1
+        ;;
+    -p | --provision)
+        _provision=true
+        shift 1
+        ;;
+    -u | --username)
+        username="$2"
+        shift 2
+        ;;
+    -c | --cleanup)
+        _cleanup=true
+        shift 1
+        ;;
+    -e | --edge-kernel)
+        _edge_kernel=true
+        shift 1
+        ;;
+    -l | --lookbusy)
+        _enable_lookbusy=true
+        shift 1
+        ;;
+    -ist | --install-speedtest)
+        _install_speedtest=true
+        shift 1
+        ;;
+    -ilb | --install-lookbusy)
+        _install_lookbusy=true
+        shift 1
+        ;;
+    -ipe | --install-pyenv)
+        _install_pyenv=true
+        shift 1
+        ;;
+    -nf | --netflix-test)
+        _netflix_test=true
+        shift 1
+        ;;
+    *)
+        POSITIONAL+=("$1")
+        shift
+        ;;
     esac
 done
 
@@ -375,7 +491,7 @@ action() {
         self_update
     elif [[ "$_remove_old_kernels" == true ]]; then
         remove_old_kernels
-    elif [[ "$_reset" == true ]] || [[ "$_reset_with_debian" == true ]] ||  [[ "$_reset_with_ubuntu" == true ]]; then
+    elif [[ "$_reset" == true ]] || [[ "$_reset_with_debian" == true ]] || [[ "$_reset_with_ubuntu" == true ]]; then
         [[ -z "$username" ]] && echo "username is required when resetting system" && return 1
         system="debi"
         [[ "$_reset_with_ubuntu" == true ]] && system="ubuntu"
