fallback to github when domain failed

diff --git a/provision b/provision
--- a/provision
+++ b/provision
@@ -79,7 +79,7 @@ function _install_neofetch() {
 }
 
 function _install_im() {
-    curl -sL debian.lol/im -o /usr/bin/im && chmod +x /usr/bin/im
+    curl -sL "$base_url/im" -o /usr/bin/im && chmod +x /usr/bin/im
     [ -f /usr/bin/im ] && installed+=("/usr/bin/im")
 }
 
@@ -141,9 +141,9 @@ function _enable_socat() {
         error "socat installation failed"
     fi
 
-    curl -sL debian.lol/socat/socat.service -o /lib/systemd/system/socat.service
-    curl -sL debian.lol/socat/socat -o /etc/socat && chmod +x /etc/socat
-    curl -sL debian.lol/socat/socatrc -o /etc/socatrc
+    curl -sL "$base_url/socat/socat.service" -o /lib/systemd/system/socat.service
+    curl -sL "$base_url/socat/socat" -o /etc/socat && chmod +x /etc/socat
+    curl -sL "$base_url/socat/socatrc" -o /etc/socatrc
 
     [ ! -f /etc/socatrc ] && error "socatrc installation failed"
     [ ! -f /etc/socat ] && error "socat installation failed"
@@ -291,6 +291,21 @@ if ((EUID != 0)); then
         gksu "$0" "$@"
     fi
     exit
+fi
+
+base_url="https://debian.lol"
+github_base="https://raw.githubusercontent.com/mysqto/install/gh-pages"
+
+# check connection to base url
+if ! curl -sL --connect-timeout 5 "$base_url" >/dev/null 2>&1; then
+    echo "Failed to connect to $base_url"
+    echo "try to use github url $github_base"
+    base_url="$github_base"
+    # check connection to base url again
+    if ! curl -sL --connect-timeout 5 "$base_url" >/dev/null 2>&1; then
+        echo "Failed to connect to $base_url"
+        exit 1
+    fi
 fi
 
 username=""
@@ -445,7 +460,7 @@ apt -y --no-install-recommends install byobu wget curl net-tools build-essential
 }
 
 [ "$install_neofetch" = true ] && _install_neofetch
-[ "$install_go" = true ] && curl -sL debian.lol/go | bash
+[ "$install_go" = true ] && curl -sL "$base_url/go" | bash
 [ "$install_im" = true ] && _install_im
 
 [ "$enable_socat" = true ] && _enable_socat
@@ -479,7 +494,7 @@ apt -y --no-install-recommends install byobu wget curl net-tools build-essential
         }
     }
 
-    curl -sL debian.lol/ss-libev | bash -s -- --password "$shadowsocks_password" --port "$shadowsocks_port" --obfs-host "$shadowsocks_obfs_host"
+    curl -sL "$base_url/ss-libev" | bash -s -- --password "$shadowsocks_password" --port "$shadowsocks_port" --obfs-host "$shadowsocks_obfs_host"
 }
 
 [ "$install_shadow_tls" = true ] && {
@@ -541,7 +556,7 @@ apt -y --no-install-recommends install byobu wget curl net-tools build-essential
         }
     }
 
-    curl -sL debian.lol/Surge/Snell/install | bash -s -- --snell-port "$snell_port" --snell-psk "$snell_psk" --snell-version "$snell_version" \
+    curl -sL "$base_url//Surge/Snell/install" | bash -s -- --snell-port "$snell_port" --snell-psk "$snell_psk" --snell-version "$snell_version" \
         --shadow-tls --shadow-tls-password "$shadow_tls_password" --shadow-tls-port "$shadow_tls_port" --obfs-host "$shadow_tls_obfs_host"
 }
 
