add `ipv6` check

diff --git a/provision b/provision
--- a/provision
+++ b/provision
@@ -1,45 +1,6 @@
 #!/usr/bin/env bash
 
-function warn() {
-    echo -e "\033[1;33m${*}\033[0m"
-}
-
-function error() {
-    echo -e "\033[1;31m${*}\033[0m"
-    exit 1
-}
-
-distribution="$(lsb_release -is 2>/dev/null)"
-
-[ -z "$distribution" ] && distribution="$(cat /etc/*-release 2>/dev/null | grep -Eo 'ID=\w+' | cut -d'=' -f2 | head -n1)"
-
-[ -z "$distribution" ] && distribution="$(cat /etc/*-release 2>/dev/null | grep -Eo 'ID_LIKE=\w+' | cut -d'=' -f2 | head -n1)"
-
-[ -z "$distribution" ] && error "Could not detect distribution"
-
-distribution="$(echo "$distribution" | tr '[:upper:]' '[:lower:]')"
-
-if [[ "$distribution" != "ubuntu" && "$distribution" != "debian" ]]; then
-    echo "This script only works on Ubuntu and Debian"
-    exit 1
-fi
-
-# check sudo installed
-if ! command -v sudo &> /dev/null; then
-    echo "sudo could not be found"
-    ((EUID == 0)) && apt update && apt install -y sudo || echo "Please install sudo first" && exit 1
-fi
-
-if ((EUID != 0)); then
-	echo "Granting root privileges for ""$(basename "$0")"
-	if [[ -t 1 ]]; then
-		sudo "$0" "$@"
-	else
-		exec 1>output_file
-		gksu "$0" "$@"
-	fi
-	exit
-fi
+installed=()
 
 nopassword=(
     apt 
@@ -68,6 +29,235 @@ nopassword=(
     make
 )
 
+
+function warn() {
+    echo -e "\033[1;33m${*}\033[0m"
+}
+
+function error() {
+    echo -e "\033[1;31m${*}\033[0m"
+    exit 1
+}
+
+function _installed() {
+    command -v "$1" &> /dev/null
+}
+
+function _install_fish() {
+    local distro="$1"
+    if [ "$distro" == "ubuntu" ]; then
+        apt install -y software-properties-common
+        add-apt-repository -y ppa:fish-shell/release-3
+    elif [ "$distro" == "debian" ]; then
+        debian_release="$(lsb_release -rs 2>/dev/null)"
+        echo "deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_$debian_release/ /" \
+            | tee /etc/apt/sources.list.d/shells:fish:release:3.list
+        curl -fsSL "https://download.opensuse.org/repositories/shells:fish:release:3/Debian_$debian_release/Release.key" \
+            | gpg --dearmor | tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
+        apt -y update
+    fi
+    apt -y --no-install-recommends install fish
+}
+
+function _install_neofetch() {
+    # install neofetch
+    pushd /tmp >> /dev/null 2>&1 || exit
+    rm -rf neofetch
+    git clone https://github.com/dylanaraps/neofetch
+    if [ -d neofetch ]; then
+        pushd neofetch >> /dev/null 2>&1 || exit
+        make install
+        popd >> /dev/null 2>&1 || exit
+    fi
+    popd >> /dev/null 2>&1 || exit
+}
+
+function _install_im() {
+    curl -sL install.lol/im -o /usr/bin/im && chmod +x /usr/bin/im
+    [ -f /usr/bin/im ] && installed+=("/usr/bin/im")
+}
+
+function _enable_bbr() {
+    if ! grep -q "bbr" /etc/sysctl.conf; then
+        echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
+        echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
+    fi
+    sysctl -p
+}
+
+function _enable_backports() {
+    echo "Enabling backports for Debian"
+    debian_codename="$(lsb_release -cs 2>/dev/null)"
+    #use backports for debian
+    apt_source_list="/etc/apt/sources.list"
+    grep -q "$debian_codename-backports" "$apt_source_list" || cat >> "$apt_source_list" <<EOF
+deb http://deb.debian.org/debian $debian_codename-backports main
+deb-src http://deb.debian.org/debian $debian_codename-backports main
+EOF
+    backports_pirority_file="/etc/apt/preferences.d/backports"
+    [ -f "$backports_pirority_file" ] && rm -f "$backports_pirority_file"
+    cat >> "$backports_pirority_file" <<EOF
+Package: *
+Pin: release a=$debian_codename-backports
+Pin-Priority: 900
+EOF
+}
+
+function _enable_ipv6() {
+    if=$(ip -6 route | grep default | awk '{print $5}')
+    if [ -z "$if" ]; then
+        warn "ipv6_dchp is true but no default ipv6 route found"
+    elif grep -q "iface $if inet6 dhcp" /etc/network/interfaces; then
+        warn "ipv6_dchp is true but ipv6 dhcp is already enabled"
+    else
+        echo "iface $if inet6 dhcp" >> /etc/network/interfaces
+    fi
+}
+
+function _enable_socat() {
+    apt -y --no-install-recommends install socat
+    if ! _installed socat; then
+        error "socat installation failed"
+    fi
+
+    curl -sL install.lol/socat/socat.service -o /lib/systemd/system/socat.service
+    curl -sL install.lol/socat/socat -o /etc/socat && chmod +x /etc/socat
+    curl -sL install.lol/socat/socatrc -o /etc/socatrc
+
+    [ ! -f /etc/socatrc ] && error "socatrc installation failed"
+    [ ! -f /etc/socat ] && error "socat installation failed"
+    [ ! -f /lib/systemd/system/socat.service ] && error "socat.service installation failed"
+
+    systemctl enable socat.service
+}
+
+function _config_ssh() {
+    [ $# -ne 2 ] && warn "config_ssh requires 2 arguments" && return 1
+    username="$1"
+    ssh_authorized_keys="$2"
+    [ -d "/home/$username/.ssh" ] && rm -rf "/home/$username/.ssh"
+    mkdir -p "/home/$username/.ssh"
+
+    if grep -q "$ssh_authorized_keys" "/home/$username/.ssh/authorized_keys"; then
+        warn "ssh_authorized_keys already exists"
+    else
+        echo "$ssh_authorized_keys" >> "/home/$username/.ssh/authorized_keys"
+    fi
+
+    chown -R "$username:$username" "/home/$username/.ssh"
+    chmod 700 /home/"$username"/.ssh
+    chmod 600 /home/"$username"/.ssh/authorized_keys
+
+    # update sshd config
+    sed -ri 's/^#?PasswordAuthentication.*/PasswordAuthentication no/g' /etc/ssh/sshd_config
+    # disable root login
+    sed -ri 's/^#?PermitRootLogin.*/PermitRootLogin no/g' /etc/ssh/sshd_config    
+}
+
+function _create_user() {
+    [ $# -ne 1 ] && warn "create_user requires username" && return 1
+    username="$1"
+    # create user if not exists
+    if ! id -u "$username" >/dev/null 2>&1; then
+        group_id=1024
+        while id -g "$group_id" >/dev/null 2>&1; do
+            group_id=$((group_id + 1))
+        done
+        groupadd -g "$group_id" "$username"
+
+        user_id=1024
+        while id -u "$user_id" >/dev/null 2>&1; do
+            user_id=$((user_id + 1))
+        done
+
+        shell="$(which fish)"
+        [ -z "$shell" ] && shell="$(which bash)"
+        useradd -m -u "$user_id" -g "$group_id" -s "$shell" -G sudo "$username"
+    fi    
+}
+
+function _config_fish() {
+    [ $# -ne 1 ] && warn "config_fish requires username" && return 1
+    username="$1"
+    if ! _installed fish; then
+        _install_fish "$distro"
+    fi
+
+    fish_shell="$(which fish 2>/dev/null)"
+    current_shell="$(getent passwd "$username" | cut -d: -f7)"
+
+    [ -n "$fish_shell" ] && [ "$current_shell" != "$fish_shell" ] && {
+        chsh -s "$fish_shell" "$username" 
+        # install fisher
+        su - "$username" -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher && fisher install mysqto/flash'
+        echo "wait 5 seconds for fisher to install plugins" && sleep 5
+    }    
+}
+
+function _config_sudo() {
+    [ $# -ne 2 ] && warn "config_sudo requires username and sudo_without_password" && return 1
+    username="$1"
+    sudo_without_password="$2"
+    [ -f "/etc/sudoers.d/$username" ] && rm -f "/etc/sudoers.d/$username"
+
+    if [ "$sudo_without_password" = true ]; then
+        echo "$username ALL=(ALL) NOPASSWD: ALL" >> "/etc/sudoers.d/$username"
+    else
+        for cmd in "${nopassword[@]}"; do
+            cmd_path="$(which "$cmd")"
+            if [ -n "$cmd_path" ]; then
+                echo "$username ALL=(ALL) NOPASSWD: $cmd_path" >> "/etc/sudoers.d/$username"
+            fi
+        done
+
+        for cmd in "${installed[@]}"; do
+            cmd_path="$(which "$cmd")"
+            if [ -n "$cmd_path" ]; then
+                echo "$username ALL=(ALL) NOPASSWD: $cmd_path" >> "/etc/sudoers.d/$username"
+            fi
+        done
+    fi
+}
+
+function _enable_byobu() {
+    [ $# -ne 1 ] && warn "enable_byobu requires username" && return 1
+    username="$1"
+    if ! _installed byobu; then
+        apt -y --no-install-recommends install byobu
+    fi
+
+    su - "$username" -c 'byobu-enable'
+}
+
+distro="$(lsb_release -is 2>/dev/null)"
+
+[ -z "$distro" ] && distro="$(cat /etc/*-release 2>/dev/null | grep -Eo 'ID=\w+' | cut -d'=' -f2 | head -n1)"
+
+[ -z "$distro" ] && distro="$(cat /etc/*-release 2>/dev/null | grep -Eo 'ID_LIKE=\w+' | cut -d'=' -f2 | head -n1)"
+
+[ -z "$distro" ] && error "Could not detect distro"
+
+distro="$(echo "$distro" | tr '[:upper:]' '[:lower:]')"
+
+[ "$distro" != "ubuntu" ] && [ "$distro" != "debian" ] && error "This script only works on Ubuntu and Debian"
+
+# check sudo installed
+if ! command -v sudo &> /dev/null; then
+    echo "sudo could not be found"
+    ((EUID == 0)) && apt update && apt install -y sudo || echo "Please install sudo first" && exit 1
+fi
+
+if ((EUID != 0)); then
+	echo "Granting root privileges for ""$(basename "$0")"
+	if [ -t 1 ]; then
+		sudo "$0" "$@"
+	else
+		exec 1>output_file
+		gksu "$0" "$@"
+	fi
+	exit
+fi
+
 # this function is borrowed from https://stackoverflow.com/a/30948155
 function _pwgen() {
 	chars='!$%^&-()_+='
@@ -77,159 +267,138 @@ function _pwgen() {
 	} | shuf | tr -d '\n'
 }
 
-provision_user=""
+username=""
 ss_password=""
-shadowsocks_config="/etc/shadowsocks-libev/config.json"
+ssh_port=
 ssh_authorized_keys=""
-setup_shadowsocks=false
-distribution="$(lsb_release -is 2>/dev/null)"
+ipv6_dchp=false
+shadowsocks_config="/etc/shadowsocks-libev/config.json"
+install_fish=false
+install_neofetch=false
+install_go=false
+install_im=false
+
+enable_bbr=false
+enable_shadowsocks=false
+enable_socat=false
+enable_byobu=false
+enable_backports=false
+sudo_without_password=false
+
+distro="$(lsb_release -is 2>/dev/null)"
 
 POSITIONAL=()
 
-while [[ $# -gt 0 ]]; do
+while [ $# -gt 0 ]; do
     case "$1" in
-        -s | --setup-shadowsocks)
-            setup_shadowsocks=true
+        --ssh | --ssh-port ) 
+            ssh_port="$2"; 
+            shift 2 
+            ;;
+        -f | --fish)
+            install_fish=true
+            shift
+            ;;
+        -bbr | --bbr)
+            enable_bbr=true
+            shift
+            ;;
+        -b | --backports)
+            enable_backports=true
+            shift
+            ;;
+        -so | --socat)
+            enable_socat=true
+            shift
+            ;;    
+        -s | --shadowsocks)
+            enable_shadowsocks=true
             shift
             ;;
         -ssp | --shadowsocks-password ) 
             ss_password="$2"; 
-            shift 2 ;;
-        -u | --user ) 
-            provision_user="$2"; 
-            shift 2 ;;
-        -k | --ssh-authorized-keys ) 
+            shift 2 
+            ;;
+        -u | --user | --username) 
+            username="$2"; 
+            shift 2 
+            ;;
+        -ak | --authorized-keys ) 
             ssh_authorized_keys="$2"; 
-            shift 2 ;;
+            shift 2 
+            ;;
+        -6 | --ipv6-dhcp )
+            ipv6_dchp=true
+            shift
+            ;;
+        -nf | --neofetch )
+            install_neofetch=true
+            shift
+            ;;
+        -g | --go )
+            install_go=true
+            shift
+            ;;
+        -im | --im )
+            install_im=true
+            shift
+            ;;
+        --sudo-without-password )
+            sudo_without_password=true
+            shift
+            ;;
+        --byobu | --enable-byobu )
+            enable_byobu=true
+            shift
+            ;;
         * ) POSITIONAL+=("$1"); shift ;;
     esac
 done
 
 set -- "${POSITIONAL[@]}" # restore positional parameters
 
-# enable PPA for fish and install software
+[ "$enable_backports" = true ] && [ "$distro" == "debian" ] && {
+    _enable_backports
+}
+
 apt update && apt upgrade -y
-if [[ "$distribution" == "ubuntu" ]]; then
-    apt install -y software-properties-common
-    add-apt-repository -y ppa:fish-shell/release-3
-elif [[ "$distribution" == "debian" ]]; then
-    debian_codename="$(lsb_release -cs 2>/dev/null)"
-    #use backports for debian
-    apt_source_list="/etc/apt/sources.list"
-    grep -q "$debian_codename-backports" "$apt_source_list" || cat >> "$apt_source_list" <<EOF
-deb http://deb.debian.org/debian $debian_codename-backports main
-deb-src http://deb.debian.org/debian $debian_codename-backports main
-EOF
-    backports_pirority_file="/etc/apt/preferences.d/backports"
-    [[ -f "$backports_pirority_file" ]] && rm -f "$backports_pirority_file"
-    cat >> "$backports_pirority_file" <<EOF
-Package: *
-Pin: release a=$debian_codename-backports
-Pin-Priority: 900
-EOF
+apt -y --no-install-recommends install byobu wget curl net-tools build-essential git vim tig
 
-    debian_release="$(lsb_release -rs 2>/dev/null)"
-    echo "deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_$debian_release/ /" \
-        | tee /etc/apt/sources.list.d/shells:fish:release:3.list
-    curl -fsSL "https://download.opensuse.org/repositories/shells:fish:release:3/Debian_$debian_release/Release.key" \
-        | gpg --dearmor | tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
-    apt -y update
-fi
+[ "$install_fish" = true ] && {
+    if ! _installed fish; then
+        _install_fish "$distro"
+    fi
+}
 
-# force to use old config
-echo 'DPkg::options { "--force-confdef"; "--force-confold"; }' > /etc/apt/apt.conf.d/local
-apt -y --no-install-recommends install fish byobu wget curl net-tools build-essential git vim \
-    openssh-server tig
 
-# install shadowsocks
-if [[ "$setup_shadowsocks" == "true" ]]; then
-    [[ -f "shadowsocks_config" ]] && ss_password="$(<"$shadowsocks_config" grep "password" 2>/dev/null | cut -d'"' -f4)"
-    [[ -z "$ss_password" ]] && ss_password="$(_pwgen)"
+[ "$install_neofetch" = true ]  && _install_neofetch
+[ "$install_go" = true ] && curl -sL install.lol/go | bash
+[ "$install_im" = true ] && _install_im
+
+[ "$enable_socat" = true ] && _enable_socat
+[ "$enable_shadowsocks" = true ] && {
+    [ -f "shadowsocks_config" ] && ss_password="$(<"$shadowsocks_config" grep "password" 2>/dev/null | cut -d'"' -f4)"
+    [ -z "$ss_password" ] && ss_password="$(_pwgen)"
     curl -sL install.lol/ss-libev | bash -s -- -p "$ss_password"
-fi
+}
 
 #enable bbr
-if ! grep -q "bbr" /etc/sysctl.conf; then
-    echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
-    echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
-fi
-sysctl -p
+[ "$enable_bbr" = true ] && _enable_bbr "$distro"
+[ "$ipv6_dchp" = true ] && _enable_ipv6
 
-# update sshd config
-sed -ri 's/^#?PasswordAuthentication.*/PasswordAuthentication no/g' /etc/ssh/sshd_config
-# disable root login
-sed -ri 's/^#?PermitRootLogin.*/PermitRootLogin no/g' /etc/ssh/sshd_config
+[ -n "$ssh_port" ] && {
+    sed -ri "s/^#?Port.*/Port $ssh_port/g" /etc/ssh/sshd_config
+}
 
-# install neofetch
-pushd /tmp >> /dev/null 2>&1 || exit
-rm -rf neofetch
-git clone https://github.com/dylanaraps/neofetch
-if [[ -d neofetch ]]; then
-    pushd neofetch >> /dev/null 2>&1 || exit
-    make install
-    popd >> /dev/null 2>&1 || exit
-fi
-popd >> /dev/null 2>&1 || exit
-
-# install go
-curl -sL install.lol/go | bash
-
-# install iss and im
-curl -sL install.lol/iss -o /usr/bin/iss && chmod +x /usr/bin/iss
-curl -sL install.lol/im -o /usr/bin/im && chmod +x /usr/bin/im
-installed=()
-[[ -f /usr/bin/iss ]] && installed+=("/usr/bin/iss")
-[[ -f /usr/bin/im ]] && installed+=("/usr/bin/im")
-
-if [[ -n "$provision_user" ]]; then
-    # create user if not exists
-    if ! id -u "$provision_user" >/dev/null 2>&1; then
-        group_id=1024
-        while id -g "$group_id" >/dev/null 2>&1; do
-            group_id=$((group_id + 1))
-        done
-        groupadd -g "$group_id" "$provision_user"
-
-        user_id=1024
-        while id -u "$user_id" >/dev/null 2>&1; do
-            user_id=$((user_id + 1))
-        done
-
-        shell="$(which fish)"
-        [[ -z "$shell" ]] && shell="$(which bash)"
-        useradd -m -u "$user_id" -g "$group_id" -s "$shell" -G sudo "$provision_user"
-    fi
-    if [[ -n "$ssh_authorized_keys" ]]; then
-        [[ -d "/home/$provision_user/.ssh" ]] && rm -rf "/home/$provision_user/.ssh"
-        mkdir -p "/home/$provision_user/.ssh"
-        echo "$ssh_authorized_keys" > "/home/$provision_user/.ssh/authorized_keys"
-        chown -R "$provision_user:$provision_user" "/home/$provision_user/.ssh"
-        chmod 700 /home/"$provision_user"/.ssh
-        chmod 600 /home/"$provision_user"/.ssh/authorized_keys
-    fi
-    current_shell="$(getent passwd "$provision_user" | cut -d: -f7)"
-    fish_shell="$(which fish)"
-    if [[ "$current_shell" != "$fish_shell" ]]; then
-        chsh -s "$fish_shell" "$provision_user"
-    fi
-
-    [[ -f "/etc/sudoers.d/$provision_user" ]] && rm -f "/etc/sudoers.d/$provision_user"
-    for cmd in "${nopassword[@]}"; do
-        cmd_path="$(which "$cmd")"
-        if [[ -n "$cmd_path" ]]; then
-            echo "$provision_user ALL=(ALL) NOPASSWD: $cmd_path" >> "/etc/sudoers.d/$provision_user"
-        fi
-    done
-
-    for cmd in "${installed[@]}"; do
-        cmd_path="$(which "$cmd")"
-        if [[ -n "$cmd_path" ]]; then
-            echo "$provision_user ALL=(ALL) NOPASSWD: $cmd_path" >> "/etc/sudoers.d/$provision_user"
-        fi
-    done
-    
-    # install fisher
-    su - "$provision_user" -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher && fisher install mysqto/flash'
-    echo "wait 5 seconds for fisher to install plugins" && sleep 5
-    su - "$provision_user" -c 'byobu-enable'
+if [ -n "$username" ]; then
+    # create user
+    _create_user "$username"
+    # config ssh
+    [ -n "$ssh_authorized_keys" ] && _config_ssh "$username" "$ssh_authorized_keys"
+    # config fish
+    _config_fish "$username"
+    # config byobu
+    [ "$enable_byobu" = true ] && _enable_byobu "$username"
+    # config sudo
+    _config_sudo "$username" "$sudo_without_password"
 fi
