disable simple-obfs doc

diff --git a/Surge/Snell/install b/Surge/Snell/install
--- a/Surge/Snell/install
+++ b/Surge/Snell/install
@@ -66,7 +66,7 @@ function download_snell() {
 
     if [ "$installed_version" == "$remove_version" ]; then
         warn "Installed snell version is $installed_version, latest snell version is $remove_version, no need to update snell!"
-        return
+        return 0
     fi
 
     download "$snell_download_url" "$snell_download_file"
@@ -96,7 +96,7 @@ function enable_snell() {
         error "Failed to create snell config dir!"
     }
 
-    cat >/etc/snell/snell-server.conf <<EOF
+    cat >"$snell_config_file" <<EOF
 # snell-server config
 # https://manual.nssurge.com/others/snell.html
 [snell-server]
@@ -158,13 +158,14 @@ function download_shadow_tls() {
     latest_release="$(curl -sL https://api.github.com/repos/$shadow_tls_repo/releases/latest 2>/dev/null | grep "tag_name" | cut -d '"' -f 4)"
     if [ "$installed_version" == "$latest_release" ]; then
         warn "Installed shadow-tls version is $installed_version, latest shadow-tls version is $latest_release, no need to update shadow-tls!"
+        return 0
     fi
     [ -z "$latest_release" ] && error "Failed to get latest release of shadow-tls"
     download_url="$(curl -sL "https://api.github.com/repos/$shadow_tls_repo/releases/tags/$latest_release" | grep "browser_download_url" | grep "$arch-.*-linux" | cut -d '"' -f 4)"
     [ -z "$download_url" ] && error "Failed to get download url of shadow-tls"
     download "$download_url" "$prefix/bin/shadow-tls"
+    [ -f "$prefix/bin/shadow-tls" ] || error "Failed to download shadow-tls"
     chmod +x "$prefix/bin/shadow-tls"
-    ! command -v shadow-tls >/dev/null 2>&1 && error "Failed to install shadow-tls"
 }
 
 function enable_shadow_tls() {
@@ -179,7 +180,7 @@ snell_port=${snell_port}
 obfs_host=${obfs_host}
 EOF
 
-    cat <<EOF >$shadow_tls_service_file
+    cat >"$shadow_tls_service_file" <<EOF
 [Unit]
 Description=Shadow-TLS Service
 Documentation=man:sstls-server
@@ -188,7 +189,7 @@ Wants=network-online.target
 
 [Service]
 Type=simple
-EnvironmentFile=/etc/default/shadow-tls
+EnvironmentFile=$shadow_tls_default_file
 CapabilityBoundingSet=CAP_NET_BIND_SERVICE
 AmbientCapabilities=CAP_NET_BIND_SERVICE
 DynamicUser=true
@@ -196,7 +197,7 @@ LimitNOFILE=32768
 SyslogIdentifier=shadow-tls
 Restart=on-failure
 RestartSec=5s
-ExecStart=shadow-tls --v3 server --listen ::0:$shadow_tls_port --server 127.0.0.1:$snell_port --tls $obfs_host  --password $shadow_tls_password
+ExecStart=shadow-tls --v3 server --listen ::0:\${shadow_tls_port} --server 127.0.0.1:\${snell_port} --tls \${obfs_host}  --password \${shadow_tls_password}
 
 [Install]
 WantedBy=multi-user.target
@@ -211,62 +212,68 @@ EOF
 [ $EUID -ne 0 ] && echo "Error: This script must be run as root!" && exit 1
 
 snell_port=
-ipv6=false
+ipv6=true
 snell_psk=
 obfs=http
 obfs_host=
-tfo=false
+tfo=true
 snell_version=
 shadow_tls=
 shadow_tls_password=
+
+POSITIONAL=()
 
 while [ $# -gt 0 ]; do
     key="$1"
     case $key in
     -sp | --snell-port)
         snell_port="$2"
-        shift
+        shift 2
         ;;
     -sv | --snell-version)
         snell_version="$2"
-        shift
+        shift 2
         ;;
     -6 | --ipv6)
         ipv6=true
+        shift
         ;;
     -spk | --snell-psk)
         snell_psk="$2"
-        shift
+        shift 2
         ;;
     -o | --obfs)
         obfs="$2"
         [ "$obfs" != "http" ] && [ "$obfs" != "tls" ] && error "Invalid obfs: $obfs" && exit 1
-        shift
+        shift 2
         ;;
     -h | --obfs-host)
         obfs_host="$2"
-        shift
+        shift 2
         ;;
     -t | --tfo)
         tfo=true
         ;;
     -s | --shadow-tls)
         shadow_tls=true
+        shift
         ;;
     -stp | --shadow-tls-port)
         shadow_tls_port="$2"
-        shift
+        shift 2
         ;;
     -spw | --shadow-tls-password)
         shadow_tls_password="$2"
-        shift
+        shift 2
         ;;
     *)
-        warn "Unknown option: $key"
+        POSITIONAL+=("$1")
+        shift
         ;;
     esac
-    shift
 done
+
+set -- "${POSITIONAL[@]}" # restore positional parameters
 
 [ -z "$snell_port" ] && {
     snell_port="$(grep 2>/dev/null <"$snell_config_file" -oE "listen = .*" | awk -F ':' '{print $NF}' | tr -d ' ')" ||
@@ -286,8 +293,8 @@ done
 [ -z "$obfs" ] && {
     obfs="$(grep 2>/dev/null <"$snell_config_file" -oE "obfs = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
     [ -z "$obfs" ] && {
-        warn "Failed to get obfs from $snell_config_file, use http as default"
-        obfs="http"
+        warn "Failed to get obfs from $snell_config_file, use tls as default"
+        obfs="tls"
     }
 }
 
