shell format

diff --git a/Surge/Snell/install b/Surge/Snell/install
--- a/Surge/Snell/install
+++ b/Surge/Snell/install
@@ -25,11 +25,12 @@ function warn() {
 
 function error() {
     echo -e "\033[1;31m${*}\033[0m"
+    exit 1
 }
 
 service_exists() {
     local n=$1
-    if [[ $(systemctl list-units --all -t service --full --no-legend "$n.service" | cut -f1 -d' ' 2>/dev/null) == $n.service ]]; then
+    if [ "$(systemctl list-units --all -t service --full --no-legend "$n.service" | cut -f1 -d' ' 2>/dev/null)" == "$n.service" ]; then
         return 0
     else
         return 1
@@ -56,7 +57,7 @@ function download_snell() {
     installed_version="$(snell-server --version 2>&1 | grep -Eo "snell-server v[0-9\.]+" | cut -d ' ' -f 2 | sed 's/ *$//g')"
     # match last https://
     snell_download_url="$(curl -sL "$snell_homepage" 2>/dev/null | grep -oE "https://[^\"]+" | grep -E "linux-$arch\.zip" | head -n 1)"
-    [[ -z "$snell_download_url" ]] && {
+    [ -z "$snell_download_url" ] && {
         error "Failed to get snell download url!"
         exit 1
     }
@@ -64,26 +65,26 @@ function download_snell() {
 
     remove_version="$(echo "$snell_download_file" | grep -oE "v[0-9\.]+" | sed 's/ *$//g')"
 
-    if [[ "$installed_version" == "$remove_version" ]]; then
+    if [ "$installed_version" == "$remove_version" ]; then
         warn "Installed snell version is $installed_version, latest snell version is $remove_version, no need to update snell!"
         return
     fi
 
     download "$snell_download_url" "$snell_download_file"
 
-    [[ -f "$snell_download_file" ]] || {
+    [ -f "$snell_download_file" ] || {
         error "Failed to download snell!"
     }
 
     unzip "$snell_download_file"
 
-    [[ -f "snell-server" ]] || {
+    [ -f "snell-server" ] || {
         error "Failed to extract snell!"
     }
 
     mv snell-server "$snell_bin"
 
-    [[ -f "$snell_bin" ]] || {
+    [ -f "$snell_bin" ] || {
         error "Failed to install snell!"
     }
 }
@@ -91,8 +92,8 @@ function download_snell() {
 function enable_snell() {
     download_snell
     # check etc dir
-    [[ -d "$snell_config_dir" ]] || mkdir -p "$snell_config_dir" 2>/dev/null
-    [[ -d "$snell_config_dir" ]] || {
+    [ -d "$snell_config_dir" ] || mkdir -p "$snell_config_dir" 2>/dev/null
+    [ -d "$snell_config_dir" ] || {
         error "Failed to create snell config dir!"
     }
 
@@ -208,7 +209,7 @@ EOF
 }
 
 # run as root
-[[ $EUID -ne 0 ]] && echo "Error: This script must be run as root!" && exit 1
+[ $EUID -ne 0 ] && echo "Error: This script must be run as root!" && exit 1
 
 snell_port=
 ipv6=false
@@ -220,7 +221,7 @@ snell_version=
 shadow_tls=
 shadow_tls_password=
 
-while [[ $# -gt 0 ]]; do
+while [ $# -gt 0 ]; do
     key="$1"
     case $key in
     -sp | --snell-port)
@@ -268,30 +269,40 @@ while [[ $# -gt 0 ]]; do
     shift
 done
 
-[ -z "$snell_port" ] && snell_port="$(grep 2>/dev/null <"$snell_config_file" -oE "listen = .*" | awk -F ':' '{print $NF}' | tr -d ' ')"
 [ -z "$snell_port" ] && {
-    snell_port=$(shuf -i 10000-65535 -n 1 2>/dev/null) ||
+    snell_port="$(grep 2>/dev/null <"$snell_config_file" -oE "listen = .*" | awk -F ':' '{print $NF}' | tr -d ' ')" ||
+        snell_port=$(shuf -i 10000-65535 -n 1 2>/dev/null) ||
         snell_port=$(awk -v min=10000 -v max=65535 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
+    [ -z "$snell_port" ] && error "Port is required, please specify it with --snell-port option"
 }
-[ -z "$snell_port" ] && error "Port is required" && exit 1
 
-[ -z "$snell_psk" ] && snell_psk="$(grep 2>/dev/null <"$snell_config_file" -oE "psk = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
 [ -z "$snell_psk" ] && {
-    snell_psk="$(pwgen -ns 32 1 2>/dev/null)" ||
+    snell_psk="$(grep 2>/dev/null <"$snell_config_file" -oE "psk = .*" | awk -F '=' '{print $NF}' | tr -d ' ')" ||
+        snell_psk="$(pwgen -ns 32 1 2>/dev/null)" ||
         snell_psk="$(uuidgen -r 2>/dev/null)" ||
         snell_psk="$(tr </dev/urandom -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 2>/dev/null)"
+    [ -z "$snell_psk" ] && error "PSK is required, please specify it with --snell-psk option"
 }
-[ -z "$snell_psk" ] && error "PSK is required" && exit 1
 
-[ -z "$obfs" ] && obfs="$(grep 2>/dev/null <"$snell_config_file" -oE "obfs = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
-[ -z "$obfs" ] && obfs="http"
+[ -z "$obfs" ] && {
+    obfs="$(grep 2>/dev/null <"$snell_config_file" -oE "obfs = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
+    [ -z "$obfs" ] && {
+        warn "Failed to get obfs from $snell_config_file, use http as default"
+        obfs="http"
+    }
+}
 
 [ -z "$obfs_host" ] && {
     obfs_host="$(grep 2>/dev/null <"$snell_config_file" -oE "obfs-host = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
 }
 
-[ -z "$snell_version" ] && snell_version=$(grep 2>/dev/null <"$snell_config_file" -oE "version = .*" | awk -F '=' '{print $NF}' | tr -d ' ')
-[ -z "$snell_version" ] && snell_version="4"
+[ -z "$snell_version" ] && {
+    snell_version=$(grep 2>/dev/null <"$snell_config_file" -oE "version = .*" | awk -F '=' '{print $NF}' | tr -d ' ')
+    [ -z "$snell_version" ] && {
+        warn "Failed to get version from $snell_config_file, use 4 as default"
+        snell_version="4"
+    }
+}
 
 [ -z "$shadow_tls" ] && {
     # check shadow-tls service exists
@@ -303,22 +314,24 @@ done
 }
 
 [ "$shadow_tls" = true ] && {
-    shadow_tls_password=$(grep 2>/dev/null <"$shadow_tls_default_file" -oE "shadow_tls_password=.*" | awk -F '=' '{print $NF}' | tr -d ' ')
+
     [ -z "$shadow_tls_password" ] && {
-        shadow_tls_password="$(pwgen -ns 32 1 2>/dev/null)" ||
+        shadow_tls_password=$(grep 2>/dev/null <"$shadow_tls_default_file" -oE "shadow_tls_password=.*" | awk -F '=' '{print $NF}' | tr -d ' ') ||
+            shadow_tls_password="$(pwgen -ns 32 1 2>/dev/null)" ||
             shadow_tls_password="$(uuidgen -r 2>/dev/null)" ||
             shadow_tls_password="$(tr </dev/urandom -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 2>/dev/null)"
+        [ -z "$shadow_tls_password" ] && error "Shadow-TLS password is required when shadow-tls is enabled"
     }
-    [ -z "$shadow_tls_password" ] && error "Shadow-TLS password is required when shadow-tls is enabled" && exit 1
 
-    shadow_tls_port=$(grep 2>/dev/null <"$shadow_tls_default_file" -oE "shadow_tls_port=.*" | awk -F '=' '{print $NF}' | tr -d ' ')
-    # should not use snell port
-    while [[ -z "$shadow_tls_port" ]] || [[ "$shadow_tls_port" -eq "$snell_port" ]]; do
-        shadow_tls_port=$(shuf -i 10000-65535 -n 1 2>/dev/null) ||
-            shadow_tls_port=$(awk -v min=10000 -v max=65535 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
-    done
-    [ -z "$shadow_tls_port" ] && error "Shadow-TLS port is required when shadow-tls is enabled" && exit 1
-    [ "$shadow_tls_port" -eq "$snell_port" ] && error "Shadow-TLS port should not be the same as snell port" && exit 1
+    [ -z "$shadow_tls_port" ] && {
+        shadow_tls_port=$(grep 2>/dev/null <"$shadow_tls_default_file" -oE "shadow_tls_port=.*" | awk -F '=' '{print $NF}' | tr -d ' ')
+        # should not use snell port
+        while [ -z "$shadow_tls_port" ] || [ "$shadow_tls_port" -eq "$snell_port" ]; do
+            shadow_tls_port=$(shuf -i 10000-65535 -n 1 2>/dev/null) ||
+                shadow_tls_port=$(awk -v min=10000 -v max=65535 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
+        done
+        [ -z "$shadow_tls_port" ] && error "Shadow-TLS port is required when shadow-tls is enabled" && exit 1
+    }
     [ "$obfs" != "tls" ] && {
         warn "Shadow-TLS is enabled but obfs is not tls, forcing obfs to tls"
         obfs="tls"
@@ -330,6 +343,7 @@ done
 }
 
 [ -z "$obfs_host" ] && {
+    warn "No obfs-host specified, use random one"
     obfs_host=${obfs_hosts[$RANDOM % ${#obfs_hosts[@]}]}
 }
 
@@ -344,8 +358,8 @@ esac
 
 wd=$(mktemp -t "snell.XXXXXXXXXXXXXXXX" -d 2>/dev/null)
 
-[[ ! -d "$wd" ]] && wd=/tmp/snell-$(date +%s) && mkdir -p "$wd" 2>/dev/null
-[[ ! -d "$wd" ]] && echo "failed to create working directory" && exit 1
+[ ! -d "$wd" ] && wd=/tmp/snell-$(date +%s) && mkdir -p "$wd" 2>/dev/null
+[ ! -d "$wd" ] && echo "failed to create working directory" && exit 1
 
 if installed apt || installed apt-get; then
     apt-get update
diff --git a/ss-libev b/ss-libev
--- a/ss-libev
+++ b/ss-libev
@@ -1,15 +1,5 @@
 #!/bin/bash
 
-# this function is borrowed from https://stackoverflow.com/a/30948155
-function _pwgen() {
-    chars='!%^&-()_+='
-    {
-        LC_ALL=C grep </dev/urandom -ao '[A-Za-z0-9]' |
-            head -n$((RANDOM % 8 + 9))
-        echo ${chars:$((RANDOM % ${#chars})):1} # Random special char.
-    } | shuf | tr -d '\n'
-}
-
 # shellcheck disable=SC2120
 function default_interface() {
     type="$1"
@@ -19,7 +9,7 @@ function default_interface() {
 
 service_exists() {
     local n=$1
-    if [[ $(systemctl list-units --all -t service --full --no-legend "$n.service" | cut -f1 -d' ' 2>/dev/null) == $n.service ]]; then
+    if [ "$(systemctl list-units --all -t service --full --no-legend "$n.service" | cut -f1 -d' ' 2>/dev/null)" == "$n.service" ]; then
         return 0
     else
         return 1
@@ -27,19 +17,36 @@ service_exists() {
 }
 
 POSITIONAL=()
+port=
 password=""
+obfs_host=""
 libsodium_version=""
-libsodium_default_version="1.0.18"
+libsodium_default_version=
 mbedtls_version=""
-mbedtls_default_version="2.28.2"
+mbedtls_default_version=
 mbed_releases_url="https://api.github.com/repos/ARMmbed/mbedtls/releases"
 libsodium_releases_url="https://api.github.com/repos/jedisct1/libsodium/releases"
 systemd_service_file=/lib/systemd/system/shadowsocks-libev.service
 
-while [[ $# -gt 0 ]]; do
+obfs_hosts=(
+    "microsoft.com"
+    "apple.com"
+    "gateway.messenger.live.com"
+    "gateway.icloud.com"
+)
+
+while [ $# -gt 0 ]; do
     case "$1" in
+    -P | --port)
+        port="$2"
+        shift 2
+        ;;
     -p | --password)
         password="$2"
+        shift 2
+        ;;
+    -o | --obfs-host)
+        obfs_host="$2"
         shift 2
         ;;
     -lsv | --libsodium-version)
@@ -59,20 +66,20 @@ done
 
 set -- "${POSITIONAL[@]}" # restore positional parameters
 
-[[ -n "$libsodium_version" ]] || {
+[ -n "$libsodium_version" ] || {
     libsodium_version=$(curl -sL "$libsodium_releases_url" 2>/dev/null | grep "tag_name" | head -n 1 | cut -d '"' -f4 | cut -d'-' -f1)
 }
-[[ -n "$mbedtls_version" ]] || {
+[ -n "$mbedtls_version" ] || {
     mbedtls_version=$(curl -sL "$mbed_releases_url" 2>/dev/null | grep "tag_name" | grep 'v2.' | head -n 1 | cut -d '"' -f 4)
 }
 
-[[ -z "$libsodium_version" ]] && echo "use libsodium $libsodium_default_version" && libsodium_version="$libsodium_default_version"
-[[ -z "$mbedtls_version" ]] && echo "use mbedtls $mbedtls_default_version" && mbedtls_version="$mbedtls_default_version"
+[ -z "$libsodium_version" ] && echo "use libsodium $libsodium_default_version" && libsodium_version="$libsodium_default_version"
+[ -z "$mbedtls_version" ] && echo "use mbedtls $mbedtls_default_version" && mbedtls_version="$mbedtls_default_version"
 
 wd=$(mktemp -t "ss-libev.XXXXXXXXXXXXXXXX" -d 2>/dev/null)
 
-[[ ! -d "$wd" ]] && wd=/tmp/$(date +%s) && mkdir -p "$wd" 2>/dev/null
-[[ ! -d "$wd" ]] && echo "failed to create working directory" && exit 1
+[ ! -d "$wd" ] && wd=/tmp/$(date +%s) && mkdir -p "$wd" 2>/dev/null
+[ ! -d "$wd" ] && echo "failed to create working directory" && exit 1
 
 pushd "$wd" >>/dev/null 2>&1 || exit
 
@@ -82,7 +89,7 @@ sudo apt -y update && DEBIAN_FRONTEND=noninteractive sudo apt -y --no-install-re
 # Installation of Libsodium
 rm -rf "libsodium"
 git clone https://github.com/jedisct1/libsodium.git "libsodium"
-[[ ! -d "libsodium" ]] && echo "failed to clone libsodium" && exit 1
+[ ! -d "libsodium" ] && echo "failed to clone libsodium" && exit 1
 pushd "libsodium" >>/dev/null 2>&1 || exit
 git checkout "$libsodium_version"
 ./autogen.sh
@@ -94,7 +101,7 @@ sudo ldconfig
 # Installation of MbedTLS
 rm -rf "mbedtls"
 git clone https://github.com/ARMmbed/mbedtls.git "mbedtls"
-[[ ! -d "mbedtls" ]] && echo "failed to clone mbedtls" && exit 1
+[ ! -d "mbedtls" ] && echo "failed to clone mbedtls" && exit 1
 pushd "mbedtls" >>/dev/null 2>&1 || exit
 git checkout "$mbedtls_version"
 make SHARED=1 CFLAGS=-fPIC
@@ -118,19 +125,35 @@ git submodule update --init --recursive
 ./autogen.sh && ./configure --prefix=/usr && make
 sudo make install
 if [ ! -e "/etc/shadowsocks-libev/config.json" ]; then
-    [[ ! -d "/etc/shadowsocks-libev/" ]] && sudo mkdir -p /etc/shadowsocks-libev/
-    [[ -z "$password" ]] && password=$(_pwgen)
+    [ ! -d "/etc/shadowsocks-libev/" ] && sudo mkdir -p /etc/shadowsocks-libev/
+    [ -z "$password" ] && {
+        password="$(pwgen -ns 32 1 2>/dev/null)" ||
+            password="$(busybox pwgen -ns 32 1 2>/dev/null)" ||
+            password="$(openssl rand -base64 32 2>/dev/null)" ||
+            password="$(busybox mkpasswd -l 32 -C 16 2>/dev/null)" ||
+            password="$(tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 32 2>/dev/null)"
+    }
+    [ -z "$port" ] && {
+        port="$(shuf -i 10000-65535 -n 1 2>/dev/null)" ||
+            port="$(awk -v min=10000 -v max=65535 'BEGIN{srand(); print int(min+rand()*(max-min+1))}' 2>/dev/null)"
+    }
+
+    [ -z "$obfs_host" ] && {
+        warn "obfs-host is not specified, use random one"
+        obfs_host=${obfs_hosts[$RANDOM % ${#obfs_hosts[@]}]}
+    }
+
     cat <<EOF >config.json
 {
         "server"      : ["::0","0.0.0.0"],
-        "server_port" : 15527,
+        "server_port" : ${port},
         "password"    : "${password}",
         "timeout"     : 300,
         "method"      : "chacha20-ietf-poly1305",
         "mode"        : "tcp_and_udp",
         "fast_open"   : true,
         "plugin"      : "obfs-server",
-        "plugin_opts" : "obfs=http;obfs-host=cloudfront.net"
+        "plugin_opts" : "obfs=http;obfs-host=${obfs_host}"
 }
 EOF
     sudo mv config.json /etc/shadowsocks-libev/
