add `shadow-tls`

diff --git a/Surge/Snell/install b/Surge/Snell/install
--- a/Surge/Snell/install
+++ b/Surge/Snell/install
@@ -4,18 +4,20 @@ snell_homepage="https://manual.nssurge.com/others/snell.html"
 snell_bin="/usr/local/bin/snell-server"
 snell_config_file="/etc/snell/snell-server.conf"
 snell_config_dir="$(dirname "$snell_config_file")"
-systemd_service_file="/lib/systemd/system/snell.service"
+snell_service_file="/lib/systemd/system/snell-server.service"
+shadow_tls_default_file="/etc/default/shadow-tls"
+shadow_tls_service_file="/lib/systemd/system/shadow-tls.service"
 shadow_tls_repo="ihciah/shadow-tls"
 obfs_hosts=(
-    "cloudfront.net"
-    "bing.com"
     "microsoft.com"
     "apple.com"
-    "akamaihd.net"
-    "edgesuite.net"
-    "fastly.net"
-    "github.com"
+    "gateway.messenger.live.com"
+    "gateway.icloud.com"
 )
+
+function installed() {
+    command -v "$1" >/dev/null 2>&1
+}
 
 function warn() {
     echo -e "\033[1;33m${*}\033[0m"
@@ -23,6 +25,15 @@ function warn() {
 
 function error() {
     echo -e "\033[1;31m${*}\033[0m"
+}
+
+service_exists() {
+    local n=$1
+    if [[ $(systemctl list-units --all -t service --full --no-legend "$n.service" | cut -f1 -d' ' 2>/dev/null) == $n.service ]]; then
+        return 0
+    else
+        return 1
+    fi
 }
 
 function download() {
@@ -40,7 +51,92 @@ function download() {
     curl --progress-bar -Lo "$target" "$url"
 }
 
+function download_snell() {
+    # remove the trailing space
+    installed_version="$(snell-server --version 2>&1 | grep -Eo "snell-server v[0-9\.]+" | cut -d ' ' -f 2 | sed 's/ *$//g')"
+    # match last https://
+    snell_download_url="$(curl -sL "$snell_homepage" 2>/dev/null | grep -oE "https://[^\"]+" | grep -E "linux-$arch\.zip" | head -n 1)"
+    [[ -z "$snell_download_url" ]] && {
+        error "Failed to get snell download url!"
+        exit 1
+    }
+    snell_download_file="$(basename "$snell_download_url")"
+
+    remove_version="$(echo "$snell_download_file" | grep -oE "v[0-9\.]+" | sed 's/ *$//g')"
+
+    if [[ "$installed_version" == "$remove_version" ]]; then
+        warn "Installed snell version is $installed_version, latest snell version is $remove_version, no need to update snell!"
+        return
+    fi
+
+    download "$snell_download_url" "$snell_download_file"
+
+    [[ -f "$snell_download_file" ]] || {
+        error "Failed to download snell!"
+    }
+
+    unzip "$snell_download_file"
+
+    [[ -f "snell-server" ]] || {
+        error "Failed to extract snell!"
+    }
+
+    mv snell-server "$snell_bin"
+
+    [[ -f "$snell_bin" ]] || {
+        error "Failed to install snell!"
+    }
+}
+
+function enable_snell() {
+    download_snell
+    # check etc dir
+    [[ -d "$snell_config_dir" ]] || mkdir -p "$snell_config_dir" 2>/dev/null
+    [[ -d "$snell_config_dir" ]] || {
+        error "Failed to create snell config dir!"
+    }
+
+    cat >/etc/snell/snell-server.conf <<EOF
+# snell-server config
+# https://manual.nssurge.com/others/snell.html
+[snell-server]
+listen = ::0:${snell_port}
+ipv6 = ${ipv6}
+psk = ${snell_psk}
+obfs = ${obfs}
+obfs-host = ${obfs_host}
+tfo = ${tfo}
+version = ${snell_version}
+EOF
+
+    # add to service
+    cat >"$snell_service_file" <<EOF
+[Unit]
+Description=Snell Proxy Service
+After=network.target
+
+[Service]
+Type=simple
+CapabilityBoundingSet=CAP_NET_BIND_SERVICE
+AmbientCapabilities=CAP_NET_BIND_SERVICE
+DynamicUser=true
+LimitNOFILE=32768
+SyslogIdentifier=snell-server
+Restart=on-failure
+RestartSec=3
+ExecStart=$snell_bin -c $snell_config_file
+
+[Install]
+WantedBy=multi-user.target
+EOF
+
+    systemctl daemon-reload
+    systemctl enable snell-server
+    systemctl restart snell-server
+}
+
 function download_shadow_tls() {
+    local arch=
     prefix="$1"
     [ -z "$prefix" ] && prefix="/usr/local"
     case "$(uname -m)" in
@@ -48,7 +144,7 @@ function download_shadow_tls() {
         arch="x86_64"
         ;;
     aarch64)
-        arch="arm64"
+        arch="aarch64"
         ;;
     armv7l)
         arch="armv7"
@@ -58,48 +154,88 @@ function download_shadow_tls() {
         ;;
     esac
     installed_version="$(shadow-tls -V 2>/dev/null | grep "shadow-tls" | cut -d ' ' -f 2)"
-    latest_release="$(curl -s https://api.github.com/repos/$shadow_tls_repo/releases/latest 2>/dev/null | grep "tag_name" | cut -d '"' -f 4)"
-    if [ "$installed_version" != "$latest_release" ]; then
-        [ -z "$latest_release" ] && err "Failed to get latest release of shadow-tls"
-        download_url="$(curl -s "https://api.github.com/repos/$shadow_tls_repo/releases/tags/$latest_release" | grep "browser_download_url" | grep "linux-*.-$arch" | cut -d '"' -f 4)"
-        [ -z "$download_url" ] && err "Failed to get download url of shadow-tls"
-        download "$download_url" "$prefix/bin/shadow-tls"
-        chmod +x "$prefix/bin/shadow-tls"
+    [ -n "$installed_version" ] && installed_version="v$installed_version"
+    latest_release="$(curl -sL https://api.github.com/repos/$shadow_tls_repo/releases/latest 2>/dev/null | grep "tag_name" | cut -d '"' -f 4)"
+    if [ "$installed_version" == "$latest_release" ]; then
+        warn "Installed shadow-tls version is $installed_version, latest shadow-tls version is $latest_release, no need to update shadow-tls!"
     fi
+    [ -z "$latest_release" ] && err "Failed to get latest release of shadow-tls"
+    download_url="$(curl -sL "https://api.github.com/repos/$shadow_tls_repo/releases/tags/$latest_release" | grep "browser_download_url" | grep "$arch-.*-linux" | cut -d '"' -f 4)"
+    [ -z "$download_url" ] && err "Failed to get download url of shadow-tls"
+    download "$download_url" "$prefix/bin/shadow-tls"
+    chmod +x "$prefix/bin/shadow-tls"
     ! command -v shadow-tls >/dev/null 2>&1 && err "Failed to install shadow-tls"
 }
 
 function enable_shadow_tls() {
-    if ! grep -q "shadow-tls" "$snell_config_file"; then
-        sed -i "s/obfs = http/obfs = tls/g" "$snell_config_file"
-        sed -i "s/obfs-host = cloudfront.net/obfs-host = /g" "$snell_config_file"
-        sed -i "s/obfs = tls/obfs = tls\n  shadow-tls = true/g" "$snell_config_file"
-    fi
+    download_shadow_tls /usr/local
+
+    cat >"$shadow_tls_default_file" <<EOF
+# shadow-tls config
+# https://manual.nssurge.com/others/shadow-tls.html
+shadow_tls_port=${shadow_tls_port}
+shadow_tls_password=${shadow_tls_password}
+snell_port=${snell_port}
+obfs_host=${obfs_host}
+EOF
+
+    cat <<EOF >$shadow_tls_service_file
+[Unit]
+Description=Shadow-TLS Service
+Documentation=man:sstls-server
+After=network-online.target
+Wants=network-online.target
+
+[Service]
+Type=simple
+EnvironmentFile=/etc/default/shadow-tls
+CapabilityBoundingSet=CAP_NET_BIND_SERVICE
+AmbientCapabilities=CAP_NET_BIND_SERVICE
+DynamicUser=true
+LimitNOFILE=32768
+SyslogIdentifier=shadow-tls
+Restart=on-failure
+RestartSec=5s
+ExecStart=shadow-tls --v3 server --listen ::0:$shadow_tls_port --server 127.0.0.1:$snell_port --tls $obfs_host  --password $shadow_tls_password
+
+[Install]
+WantedBy=multi-user.target
+EOF
+
+    systemctl daemon-reload
+    systemctl enable shadow-tls
+    systemctl restart shadow-tls
 }
 
 # run as root
 [[ $EUID -ne 0 ]] && echo "Error: This script must be run as root!" && exit 1
 
-port=
+snell_port=
 ipv6=false
-psk=
+snell_psk=
 obfs=http
-obfs_host=cloudfront.net
+obfs_host=
 tfo=false
-shadow_tls=false
+snell_version=
+shadow_tls=
+shadow_tls_password=
 
 while [[ $# -gt 0 ]]; do
     key="$1"
     case $key in
-    -p | --port)
-        port="$2"
+    -sp | --snell-port)
+        snell_port="$2"
+        shift
+        ;;
+    -sv | --snell-version)
+        snell_version="$2"
         shift
         ;;
     -6 | --ipv6)
         ipv6=true
         ;;
-    -P | --psk)
-        psk="$2"
+    -spk | --snell-psk)
+        snell_psk="$2"
         shift
         ;;
     -o | --obfs)
@@ -117,40 +253,91 @@ while [[ $# -gt 0 ]]; do
     -s | --shadow-tls)
         shadow_tls=true
         ;;
+    -stp | --shadow-tls-port)
+        shadow_tls_port="$2"
+        shift
+        ;;
+    -spw | --shadow-tls-password)
+        shadow_tls_password="$2"
+        shift
+        ;;
     *)
         warn "Unknown option: $key"
         ;;
     esac
     shift
 done
-[ -z "$port" ] && port="$(grep <"$snell_config_file" -oE "listen = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
-[ -z "$port" ] && {
-    port=$(shuf -i 10000-65535 -n 1 2>/dev/null) ||
-        port=$(awk -v min=10000 -v max=65535 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
-}
-[ -z "$port" ] && error "Port is required" && exit 1
 
-[ -z "$psk" ] && psk="$(grep <"$snell_config_file" -oE "psk = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
-[ -z "$psk" ] && {
-    psk="$(pwgen -ns 32 1 2>/dev/null)" ||
-        psk="$(uuidgen -r 2>/dev/null)" ||
-        psk="$(tr </dev/urandom -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 2>/dev/null)"
+[ -z "$snell_port" ] && snell_port="$(grep 2>/dev/null <"$snell_config_file" -oE "listen = .*" | awk -F ':' '{print $NF}' | tr -d ' ')"
+[ -z "$snell_port" ] && {
+    snell_port=$(shuf -i 10000-65535 -n 1 2>/dev/null) ||
+        snell_port=$(awk -v min=10000 -v max=65535 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
 }
-[ -z "$psk" ] && error "PSK is required" && exit 1
+[ -z "$snell_port" ] && error "Port is required" && exit 1
 
-[ -z "$obfs" ] && obfs="$(grep <"$snell_config_file" -oE "obfs = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
+[ -z "$snell_psk" ] && snell_psk="$(grep 2>/dev/null <"$snell_config_file" -oE "psk = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
+[ -z "$snell_psk" ] && {
+    snell_psk="$(pwgen -ns 32 1 2>/dev/null)" ||
+        snell_psk="$(uuidgen -r 2>/dev/null)" ||
+        snell_psk="$(tr </dev/urandom -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 2>/dev/null)"
+}
+[ -z "$snell_psk" ] && error "PSK is required" && exit 1
+
+[ -z "$obfs" ] && obfs="$(grep 2>/dev/null <"$snell_config_file" -oE "obfs = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
 [ -z "$obfs" ] && obfs="http"
 
-[ -z "$obfs_host" ] && obfs_host="$(grep <"$snell_config_file" -oE "obfs-host = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
+[ -z "$obfs_host" ] && {
+    obfs_host="$(grep 2>/dev/null <"$snell_config_file" -oE "obfs-host = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
+}
+
+[ -z "$snell_version" ] && snell_version=$(grep 2>/dev/null <"$snell_config_file" -oE "version = .*" | awk -F '=' '{print $NF}' | tr -d ' ')
+[ -z "$snell_version" ] && snell_version="4"
+
+[ -z "$shadow_tls" ] && {
+    # check shadow-tls service exists
+    if service_exists shadow-tls; then
+        shadow_tls=true
+    else
+        command -v shadow-tls >/dev/null 2>&1 && shadow_tls=true
+    fi
+}
+
+[ "$shadow_tls" = true ] && {
+    shadow_tls_password=$(grep 2>/dev/null <"$shadow_tls_default_file" -oE "shadow_tls_password=.*" | awk -F '=' '{print $NF}' | tr -d ' ')
+    [ -z "$shadow_tls_password" ] && {
+        shadow_tls_password="$(pwgen -ns 32 1 2>/dev/null)" ||
+            shadow_tls_password="$(uuidgen -r 2>/dev/null)" ||
+            shadow_tls_password="$(tr </dev/urandom -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 2>/dev/null)"
+    }
+    [ -z "$shadow_tls_password" ] && error "Shadow-TLS password is required when shadow-tls is enabled" && exit 1
+
+    shadow_tls_port=$(grep 2>/dev/null <"$shadow_tls_default_file" -oE "shadow_tls_port=.*" | awk -F '=' '{print $NF}' | tr -d ' ')
+    # should not use snell port
+    while [[ -z "$shadow_tls_port" ]] || [[ "$shadow_tls_port" -eq "$snell_port" ]]; do
+        shadow_tls_port=$(shuf -i 10000-65535 -n 1 2>/dev/null) ||
+            shadow_tls_port=$(awk -v min=10000 -v max=65535 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
+    done
+    [ -z "$shadow_tls_port" ] && error "Shadow-TLS port is required when shadow-tls is enabled" && exit 1
+    [ "$shadow_tls_port" -eq "$snell_port" ] && error "Shadow-TLS port should not be the same as snell port" && exit 1
+    [ "$obfs" != "tls" ] && {
+        warn "Shadow-TLS is enabled but obfs is not tls, forcing obfs to tls"
+        obfs="tls"
+    }
+
+    [ -z "$obfs_host" ] && {
+        obfs_host="$(grep 2>/dev/null <"$shadow_tls_default_file" -oE "obfs_host=.*" | awk -F '=' '{print $NF}' | tr -d ' ')"
+    }
+}
+
 [ -z "$obfs_host" ] && {
     obfs_host=${obfs_hosts[$RANDOM % ${#obfs_hosts[@]}]}
 }
 
 arch=""
 case $(uname -m) in
-i386 | i686) arch="386" ;;
+i386 | i686) arch="i386" ;;
 x86_64) arch="amd64" ;;
-aarch64 | arm64 | armv8) arch="arm64" ;;
+aarch64 | arm64 | armv8) arch="aarch64" ;;
 armv7* | armv6*) arch="armv7l" ;;
 *) error "Unsupported architecture: $(uname -m)" && exit 1 ;;
 esac
@@ -160,82 +347,34 @@ wd=$(mktemp -t "snell.XXXXXXXXXXXXXXXX" -d 2>/dev/null)
 [[ ! -d "$wd" ]] && wd=/tmp/snell-$(date +%s) && mkdir -p "$wd" 2>/dev/null
 [[ ! -d "$wd" ]] && echo "failed to create working directory" && exit 1
 
+if installed apt || installed apt-get; then
+    apt-get update
+    apt-get install -y wget curl unzip
+elif installed yum; then
+    yum install -y wget curl unzip
+elif installed pacman; then
+    pacman -Sy --noconfirm wget curl unzip
+elif installed apk; then
+    apk update
+    apk add --no-cache -y wget curl unzip
+fi
+
 pushd "$wd" >>/dev/null 2>&1 || exit
-
-# match last https://
-snell_download_url="$(curl -sL "$snell_homepage" | grep -oE "https://[^\"]+" | grep -E "linux-$arch\.zip" | head -n 1)"
-[[ -z "$snell_download_url" ]] && {
-    error "Failed to get snell download url!"
-    exit 1
+warn "####################################################################"
+warn "Snell is a fast proxy tunnel that helps you bypass firewalls"
+warn "Snell version:                             ${snell_version}"
+warn "Snell port:                                ${snell_port}"
+warn "Snell PSK:                                 ${snell_psk}"
+warn "Snell obfs:                                ${obfs}"
+warn "Snell obfs-host:                           ${obfs_host}"
+warn "Shadow-TLS is enabled:                     ${shadow_tls}"
+[ "$shadow_tls" = true ] && {
+    warn "Shadow-TLS port:                           ${shadow_tls_port}"
+    warn "Shadow-TLS password:                       ${shadow_tls_password}"
 }
-snell_download_file="$(basename "$snell_download_url")"
-
-download "$snell_download_url" "$snell_download_file"
-
-[[ -f "$snell_download_file" ]] || {
-    error "Failed to download snell!"
-}
-
-unzip "$snell_download_file"
-
-[[ -f "snell-server" ]] || {
-    error "Failed to extract snell!"
-}
-
-mv snell-server "$snell_bin"
-
+warn "####################################################################"
+enable_snell
+[ "$shadow_tls" = true ] && enable_shadow_tls
 popd >>/dev/null 2>&1 || exit
 
 rm -rf "$wd"
-
-[[ -f "$snell_bin" ]] || {
-    error "Failed to install snell!"
-}
-
-# check etc dir
-[[ -d "$snell_config_dir" ]] || mkdir -p "$snell_config_dir" 2>/dev/null
-[[ -d "$snell_config_dir" ]] || {
-    error "Failed to create snell config dir!"
-}
-
-[[ -f /etc/snell/snell-server.conf ]] || {
-    cat >/etc/snell/snell-server.conf <<EOF
-# snell-server config
-# https://manual.nssurge.com/others/snell.html
-[snell-server]
-listen = ::0:${port}
-ipv6 = ${ipv6}
-psk = ${psk}
-obfs = ${obfs}
-obfs-host = ${obfs_host}
-tfo = ${tfo}
-EOF
-}
-
-# add to service
-[[ -f "$systemd_service_file" ]] || {
-    cat >"$systemd_service_file" <<EOF
-[Unit]
-Description=Snell Proxy Service
-After=network.target
-
-[Service]
-Type=simple
-User=nobody
-Group=nogroup
-LimitNOFILE=32768
-ExecStart=$snell_bin -c $snell_config_file
-AmbientCapabilities=CAP_NET_BIND_SERVICE
-StandardOutput=syslog
-StandardError=syslog
-SyslogIdentifier=snell-server
-Restart=on-failure
-RestartSec=3
-
-[Install]
-WantedBy=multi-user.target
-EOF
-}
-
-systemctl enable snell.service
-systemctl restart snell.service
diff --git a/debian b/debian
--- a/debian
+++ b/debian
@@ -41,7 +41,9 @@ function download() {
     fi
     [ -f "$target" ] && rm -rf "$target"
     echo "Downloading $url to $target"
-    curl --progress-bar -Lo "$target" "$url"
+    if ! curl --progress-bar -sf -Lo "$target" "$url"; then
+        error "Failed to download $url"
+    fi
 }
 
 function cidr_to_netmask() {
@@ -223,6 +225,7 @@ packages="net-tools curl wget git tig build-essential vim"
 # extra packages config
 install_shadowsocks=false
 shadowsocks_password=
+shadowsocks_config="/etc/shadowsocks-libev/config.json"
 install_socat=false
 ssh_port=
 install_go=false
@@ -233,7 +236,17 @@ use_backports=false
 byobu=false
 sudo_without_password=false
 
-shadowsocks_config="/etc/shadowsocks-libev/config.json"
+# Shadow-TLS related
+install_shadow_tls=
+snell_port=
+snell_psk=
+shadow_tls_port=
+shadow_tls_password=
+shadow_tls_obfs_host=
+snell_version=4
+snell_config_file="/etc/snell/snell-server.conf"
+shadow_tls_default_file="/etc/default/shadow-tls"
+
 boot_dir="/boot"
 grub_d="/etc/grub.d"
 grub_custom_file="$grub_d/40_custom"
@@ -252,20 +265,20 @@ fi
 
 [ -z "$arch" ] && {
     arch=$(dpkg --print-architecture 2>/dev/null) || {
-    case $(uname -m) in
-    x86_64)
-        arch=amd64
-        ;;
-    aarch64)
-        arch=arm64
-        ;;
-    i386)
-        arch=i386
-        ;;
-    *)
-        err 'No "--architecture" specified'
-        ;;
-    esac
+        case $(uname -m) in
+        x86_64)
+            arch=amd64
+            ;;
+        aarch64)
+            arch=arm64
+            ;;
+        i386)
+            arch=i386
+            ;;
+        *)
+            err 'No "--architecture" specified'
+            ;;
+        esac
     }
 }
 
@@ -427,6 +440,7 @@ while [ $# -gt 0 ]; do
     --provision)
         version=sid
         install_shadowsocks=true
+        install_shadow_tls=true
         install_go=true
         install_im=true
         install_fish=true
@@ -442,6 +456,30 @@ while [ $# -gt 0 ]; do
         ;;
     -aku | --authorized-keys-url)
         authorized_keys_url="$2"
+        shift 2
+        ;;
+    -stls | --shadow-tls)
+        install_shadow_tls=true
+        shift
+        ;;
+    --shadow-tls-port)
+        shadow_tls_port="$2"
+        shift 2
+        ;;
+    --shadow-tls-password)
+        shadow_tls_password="$2"
+        shift 2
+        ;;
+    --snell-port)
+        snell_port="$2"
+        shift 2
+        ;;
+    --snell-psk)
+        snell_psk="$2"
+        shift 2
+        ;;
+    --shadow-tls-obfs)
+        shadow_tls_obfs_host="$2"
         shift 2
         ;;
     -ssp | --shadowsocks-password)
@@ -551,7 +589,7 @@ esac
     memory_size=$(awk '/MemTotal/ {print $2}' /proc/meminfo 2>/dev/null)
     [ -n "$memory_size" ] || force_lowmem=0
     [ "$memory_size" -le "524288" ] && {
-        warn "memory size is less than 512MB, force to use low memory mode & cloud kernel"
+        warn "memory size <= 512MB, force to use low memory mode & cloud kernel"
         force_lowmem=1
         cloud_kernel=true
         bpo_kernel=true
@@ -659,6 +697,46 @@ fi
         shadowsocks_password="$(tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 32 2>/dev/null)"
 }
 
+[ "$install_shadow_tls" = true ] && {
+    [ -z "$snell_port" ] && snell_port="$(grep 2>/dev/null <"$snell_config_file" -oE "listen = .*" | awk -F ':' '{print $NF}' | tr -d ' ')"
+    [ -z "$snell_port" ] && {
+        snell_port=$(shuf -i 10000-65535 -n 1 2>/dev/null) ||
+            snell_port=$(awk -v min=10000 -v max=65535 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
+    }
+    [ -z "$snell_port" ] && error "Snell port is required with --shadow-tls, please re-run the script with --snell-port option"
+
+    [ -z "$snell_psk" ] && snell_psk="$(grep 2>/dev/null <"$snell_config_file" -oE "psk = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
+    [ -z "$snell_psk" ] && {
+        snell_psk="$(pwgen -ns 32 1 2>/dev/null)" ||
+            snell_psk="$(uuidgen -r 2>/dev/null)" ||
+            snell_psk="$(tr </dev/urandom -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 2>/dev/null)"
+    }
+    [ -z "$snell_psk" ] && error "Snell PSK is required with --shadow-tls, please re-run the script with --snell-psk option"
+
+    shadow_tls_password=$(grep 2>/dev/null <"$shadow_tls_default_file" -oE "shadow_tls_password=.*" | awk -F '=' '{print $NF}' | tr -d ' ')
+    [ -z "$shadow_tls_password" ] && {
+        shadow_tls_password="$(pwgen -ns 32 1 2>/dev/null)" ||
+            shadow_tls_password="$(uuidgen -r 2>/dev/null)" ||
+            shadow_tls_password="$(tr </dev/urandom -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 2>/dev/null)"
+    }
+
+    shadow_tls_port=$(grep 2>/dev/null <"$shadow_tls_default_file" -oE "shadow_tls_port=.*" | awk -F '=' '{print $NF}' | tr -d ' ')
+    # should not use snell port
+    while [[ -z "$shadow_tls_port" ]] || [[ "$shadow_tls_port" -eq "$snell_port" ]]; do
+        shadow_tls_port=$(shuf -i 10000-65535 -n 1 2>/dev/null) ||
+            shadow_tls_port=$(awk -v min=10000 -v max=65535 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
+    done
+    [ -z "$shadow_tls_port" ] && error "Shadow TLS port is required with --shadow-tls, please re-run the script with --shadow-tls-port option"
+
+    [ -z "$shadow_tls_obfs_host" ] && {
+        shadow_tls_obfs_host="$(grep 2>/dev/null <"$snell_config_file" -oE "obfs-host = .*" | awk -F '=' '{print $NF}' | tr -d ' ')" ||
+            shadow_tls_obfs_host="$(grep 2>/dev/null <"$shadow_tls_default_file" -oE "obfs_host=.*" | awk -F '=' '{print $NF}' | tr -d ' ')"
+    }
+    [ -z "$shadow_tls_obfs_host" ] && error "Shadow TLS obfs host is required with --shadow-tls, please re-run the script with --shadow-tls-obfs-host option"
+    [ -z "$snell_version" ] && snell_version="$(grep 2>/dev/null <"$snell_config_file" -oE "version = .*" | awk -F '=' '{print $NF}' | tr -d ' ')"
+    [ -z "$snell_version" ] && snell_version=4
+}
+
 [ -n "$authorized_keys_url" ] && {
     authorized_keys="$(curl -sL "$authorized_keys_url" 2>/dev/null)" ||
         authorized_keys="$(wget -qO- "$authorized_keys_url" 2>/dev/null)" ||
@@ -721,6 +799,14 @@ warn "dns:                     $dns"
 warn "ssh port:                $ssh_port"
 [ -n "$ssh_private_key" ] && warn "ssh private key: \n$ssh_private_key"
 [ -n "$authorized_keys" ] && warn "ssh public key: \n$authorized_keys"
+warn "install Shadow TLS       $install_shadow_tls"
+[ "$install_shadow_tls" = true ] && {
+    warn "snell port:              $snell_port"
+    warn "snell psk:               $snell_psk"
+    warn "shadow-tls port:         $shadow_tls_port"
+    warn "shadow-tls password:     $shadow_tls_password"
+    warn "shadow-tls obfs host:    $shadow_tls_obfs_host"
+}
 warn "#######################################################################"
 
 preseed_file="$wd/preseed.cfg"
@@ -744,13 +830,13 @@ d-i netcfg/dhcpv6_timeout string 60
 EOF
 
 if [ "$static_ip" = true ]; then
-# Static IP configuration.
+    # Static IP configuration.
     cat >>"$preseed_file" <<EOF
 # Static IP configuration.
 d-i netcfg/disable_autoconfig boolean true
 EOF
 else
-# DHCP configuration.
+    # DHCP configuration.
     cat >>"$preseed_file" <<EOF
 # DHCP configuration.
 d-i netcfg/dhcp_failed note
@@ -1030,6 +1116,14 @@ fi
 [ "$use_backports" = true ] && late_command="$late_command --backports"
 [ "$byobu" = true ] && late_command="$late_command --byobu"
 [ "$sudo_without_password" = true ] && late_command="$late_command --sudo-without-password"
+[ "$install_shadow_tls" = true ] && {
+    late_command="$late_command --shadow-tls"
+    late_command="$late_command --shadow-tls-password \"$shadow_tls_password\""
+    late_command="$late_command --shadow-tls-port \"$shadow_tls_port\""
+    late_command="$late_command --shadow-tls-obfs \"$shadow_tls_obfs_host\""
+    late_command="$late_command --snell-port \"$snell_port\""
+    late_command="$late_command --snell-psk \"$snell_psk\""
+}
 
 [ -n "$late_command" ] && {
     cat >>"$preseed_file" <<EOF
@@ -1057,7 +1151,8 @@ download "$base_url/initrd.gz" initrd.gz
 [ ! -f "initrd.gz" ] && error "Failed to download $base_url/initrd.gz"
 [ "$firmware" = true ] && [ ! -f "firmware.cpio.gz" ] && error "Failed to download $firmware_url"
 
-gzip -d initrd.gz
+gzip -d initrd.gz 2>/dev/null || error "Failed to decompress initrd.gz"
+[ ! -f initrd ] && error "Failed to decompress initrd.gz"
 # cpio reads a list of file names from the standard input
 echo preseed.cfg | cpio -o -H newc -A -F initrd
 gzip -1 initrd
